"""Command-line entry point for the Mini Local Analytics Assistant.

Pipeline: question -> generate SQL -> validate -> execute -> natural-language
answer, plus a chart when the question explicitly asks for one.
"""

from __future__ import annotations

import logging
import sys

import history_repository
from analytics_service import AnalysisResponse, process_question
from chart import ChartError, create_chart, terminal_link
from config import ConfigurationError, DISPLAY_ROWS, require_groq_api_key
from database import (
    DatabaseError,
    QueryResult,
    SqlValidationError,
    close_connection,
    initialize_database,
    run_query,
)
from llm import generate_answer, generate_conceptual_answer, generate_plan, generate_sql
from logging_config import setup_logging

logger = logging.getLogger(__name__)

SEPARATOR = "-" * 40

EXIT_OK = 0
EXIT_FAILURE = 1
EXIT_CONFIG_ERROR = 2
EXIT_INTERRUPTED = 130

# Typed words that end the session, in addition to a blank line.
EXIT_COMMANDS = frozenset({"exit", "quit"})


def render_result(result: QueryResult) -> str:
    """Format a query result for the terminal."""
    if result.is_empty:
        return "No rows matched. Columns: " + ", ".join(result.columns)

    visible = result.frame.head(DISPLAY_ROWS)
    lines = [visible.to_string(index=False), ""]

    if result.truncated:
        lines.append(
            f"Rows: {result.row_count} (capped at {result.max_rows}; "
            "the query matched more)"
        )
    else:
        lines.append(f"Rows: {result.row_count}")

    if result.row_count > DISPLAY_ROWS:
        lines.append(f"Showing the first {DISPLAY_ROWS}.")

    return "\n".join(lines)


def log_details(sql: str, result: QueryResult) -> None:
    """Record the SQL and row count that produced an answer.

    Deliberately logged rather than printed: the CLI shows the answer, not the
    machinery behind it. This is logged at INFO because the only other record of
    the statement is a DEBUG line in llm.py, which the default file level does
    not capture, so removing it from the screen would otherwise lose it entirely.
    """
    if result.truncated:
        logger.info(
            "Answered using SQL: %s | rows=%s (capped at %s, the query matched more)",
            sql,
            result.row_count,
            result.max_rows,
        )
    else:
        logger.info("Answered using SQL: %s | rows=%s", sql, result.row_count)


def emit_chart(question: str, result: QueryResult) -> None:
    """Draw a chart for a result and print a link to it. Never raises.

    A charting failure must not damage an answer that already succeeded, so every
    error is contained here.
    """
    try:
        path, chart_type, note = create_chart(question, result)
    except ChartError as exc:
        logger.warning("Chart not generated: %s", exc)
        print(f"\nChart not generated: {exc}")
        return
    except Exception:
        logger.exception("Unexpected error while generating the chart.")
        print("\nChart not generated: an unexpected error occurred. See logs/app.log.")
        return

    if note:
        print(f"\n{note}")

    print("\nChart generated successfully:")
    # Escape sequences would be printed as noise by anything that is not an
    # interactive terminal, so pipes and redirects get the plain path.
    print(terminal_link(path, supports_links=sys.stdout.isatty()))


def emit_chart_response(response: AnalysisResponse) -> None:
    """Print a chart outcome already generated by the shared service.

    This adapter intentionally never creates a chart. The service generated any
    chart from the same QueryResult that supplied the answer and result table.
    """
    if response.chart_error:
        print(f"\nChart not generated: {response.chart_error}")
        return
    if response.chart_path is None:
        return

    if response.chart_note:
        print(f"\n{response.chart_note}")

    print("\nChart generated successfully:")
    print(terminal_link(response.chart_path, supports_links=sys.stdout.isatty()))


def save_completed_history(response: AnalysisResponse) -> bool:
    """Persist one completed CLI analysis. Never raises.

    The CLI and the web adapter both persist their own completed responses, so
    the shared analytics service stays free of storage concerns. Only values
    already present on the finished response are written: no query, no model
    call, and no chart work happens here.
    """
    try:
        history_repository.save_history(
            original_question=response.original_question,
            answer=response.answer,
            row_count=response.result.row_count if response.result is not None else None,
            truncated=bool(response.result.truncated) if response.result is not None else False,
            max_rows=response.result.max_rows if response.result is not None else None,
            chart_requested=response.chart_requested,
            chart_type=response.chart_type.value if response.chart_type else None,
            chart_filename=response.chart_path.name if response.chart_path else None,
            chart_note=response.chart_note,
            answer_fallback_used=response.answer_fallback_used,
            refused=response.refused,
            success=not response.answer_fallback_used,
            elapsed_seconds=response.elapsed_seconds,
            error_code="chart_failed" if response.chart_error else None,
        )
        return True
    except Exception as exc:
        # Never let a history problem disturb a completed terminal answer.
        logger.error("History persistence failed for a completed analysis: %s", str(exc))
        return False


def answer_question(question: str) -> bool:
    """Run one question through the pipeline. Never raises; returns success."""
    try:
        response = process_question(
            question,
            plan_generator=generate_plan,
            query_runner=run_query,
            answer_generator=generate_answer,
            conceptual_answer_generator=generate_conceptual_answer,
            chart_creator=create_chart,
            query_logger=log_details,
        )
    except ValueError as exc:
        # Empty/invalid question, or generated SQL that failed validation.
        logger.warning("Could not produce valid SQL: %s", exc)
        print(f"Unable to generate SQL: {exc}")
        return False
    except RuntimeError as exc:
        logger.error("Groq request failed: %s", exc)
        print(f"Unable to reach the language model: {exc}")
        return False
    except SqlValidationError as exc:
        # Subclass of DatabaseError, so it must be caught first.
        logger.error("Execution refused: %s", exc)
        print(f"Refused to execute the generated SQL: {exc}")
        return False
    except DatabaseError as exc:
        logger.error("Execution failed: %s", exc)
        print(f"Query failed: {exc}")
        return False
    except Exception:
        logger.exception("Unexpected error while executing the query.")
        print("An unexpected error occurred. See logs/app.log for details.")
        return False

    # A refusal is not a SQL statement and must not be executed or printed as one.
    if response.refused:
        print("\nAnswer:")
        print(response.answer)
        save_completed_history(response)
        return True

    if response.answer_fallback_used:
        # The shared service has already logged diagnostic details through the
        # redaction-aware logger. Keep terminal output free of provider and
        # internal exception text while preserving the authoritative result.
        logger.error(
            "Answer generation failed; displaying the query result fallback: %s",
            str(response.answer_error),
        )
        print("\nAnswer:")
        print("The natural-language answer could not be generated.")
        print("Showing the query result instead:")
        print(render_result(response.result))
    else:
        print("\nAnswer:")
        print(response.answer)

    # The service generated any chart from the same QueryResult used above. This
    # adapter only displays the outcome, so it cannot cause a second execution.
    if response.chart_requested:
        emit_chart_response(response)

    save_completed_history(response)
    return not response.answer_fallback_used


def _use_utf8_streams() -> None:
    """Read and write UTF-8 regardless of the console code page.

    Windows terminals default to a legacy code page, which turns an em dash or a
    curly quote in a typed question into mojibake before the pipeline ever sees
    it -- and that corruption then reaches the model and the chart title.
    """
    for stream in (sys.stdin, sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):  # already closed, or not a text stream
            pass


def main() -> int:
    """Run the interactive question loop and return a process exit code."""
    _use_utf8_streams()
    setup_logging()
    logger.info("Application started.")

    # Fail fast on missing configuration, before any database work is done.
    try:
        require_groq_api_key()
    except ConfigurationError as exc:
        logger.critical("Configuration error: %s", exc)
        print(f"Configuration error: {exc}")
        return EXIT_CONFIG_ERROR

    try:
        initialize_database()
    except DatabaseError as exc:
        logger.critical("Database initialization failed: %s", exc)
        print(f"Database initialization failed: {exc}")
        return EXIT_FAILURE

    # History is a separate store; failing to prepare it must not stop analytics.
    try:
        history_repository.initialize_history_database()
    except Exception:
        logger.exception("History storage could not be initialized.")

    try:
        print(SEPARATOR)
        print("Database initialized successfully")
        print("Ask a business question. Blank line or 'exit' to quit.")

        while True:
            try:
                question = input("\nQuestion: ")
            except (EOFError, KeyboardInterrupt):
                # Ctrl+C or closed stdin exits quietly, without a traceback.
                print()
                logger.info("Session ended by the user.")
                return EXIT_INTERRUPTED

            if not question.strip() or question.strip().lower() in EXIT_COMMANDS:
                logger.info("Session ended.")
                return EXIT_OK

            # Errors for one question must not end the session.
            answer_question(question)
    except Exception:
        logger.exception("Unexpected error in the main loop.")
        print("An unexpected error occurred. See logs/app.log for details.")
        return EXIT_FAILURE
    finally:
        close_connection()
        logger.info("Application finished.")


if __name__ == "__main__":
    sys.exit(main())
